### PR TITLE
Update bypass-roblox.bat

### PR DESCRIPTION
**Pull request by Deniied**

### CODE REVIEW

**Comment by CinnamonPhysicist** [comment]
For me, they still return `{"errors":[{"code":0,"message":"Service Undergoing Maintenance"}]}` so I don't see the point

**Comment by Deniied** [comment]
> 
> 
> For me, they still return `{"errors":[{"code":0,"message":"Service Undergoing Maintenance"}]}` so I don't see the point

It was just an attempt to get APIs working but I think it would be best to add this anyways

**Comment by Flawless-sys** [comment]
> > For me, they still return `{"errors":[{"code":0,"message":"Service Undergoing Maintenance"}]}` so I don't see the point
> 
> It was just an attempt to get APIs working but I think it would be best to add this anyways

Not really if the APIs don't do anything.

**Comment by h0nde** [comment]
Haha, I tried this yesterday but they have all API endpoints blocked. It'd just make the script harder to read for no benefits in-exchange.

**Comment by h0nde** [comment]
Roblox unblocked the endpoints, I added your changes.

**Pull request closed without merging**
