### PR TITLE
set ip by ping instead of hardcoded

### PR DESCRIPTION
**Pull request by 39p**
ips are going up and down, so getting the most recent/closest one with ping should be better.

### CODE REVIEW

**Comment by xhayper** [comment]
Don't forget to update the Revert code too, since the ip is dynamic, change from matching the whole string to only the end

**Comment by 39p** [comment]
> Don't forget to update the Revert code too, since the ip is dynamic, change from matching the whole string to only the end

oh ya but I'm pretty sure all the ips start with 128.116 so you could just trim it to just that
https://github.com/h0nde/roblox-maintenance-bypass/blob/1b64b566f5f5aee6bbd12cf2a0a57c73e9de81ea/revert-changes.bat#L3

or remove based if it has roblox.com

**Comment by xhayper** [comment]
You sure it will always start with  `128.116.`?

**Comment by h0nde** [comment]
This sounds like a great idea, but I'm unsure about how you're expecting this code to work. `gold.roblox.com` is `128.116.114.3`, which is the server we're trying to avoid with the script.

**Comment by 39p** [comment]
> This sounds like a great idea, but I'm unsure about how you're expecting this code to work. `gold.roblox.com` is `128.116.114.3`, which is the server we're trying to avoid with the script in the first place.

huh strange, before I pushed I got `128.116.127.3` or `128.116.126.3` but now I'm getting that IP, guess something changed. I would assume it's always gonna return that so I'ma close this. Tho here's an list of ips that I got before it kept returning that

128.116.114.3
128.116.117.3
128.116.102.3
128.116.127.3
128.116.101.3

**Comment by xhayper** [comment]
Gotcha, Found a link that returns the correct IP.
https://gamepersistence.roblox.com/

**Pull request closed without merging**
